# --- COMA specific parameters ---

action_selector: "multinomial"
epsilon_start: .8
epsilon_finish: .01
epsilon_anneal_time: 2000000
mask_before_softmax: False

runner: "parallel"

buffer_size: 32
batch_size_run: 32
batch_size: 32

# update the target network every {} training steps
target_update_interval: 200

lr: 0.0005
critic_lr: 0.001
td_lambda: 1.0

# use COMA
agent_output_type: "pi_logits"
learner: "coma_learner"
critic_q_fn: "coma"
critic_baseline_fn: "coma"
critic_train_mode: "seq"
critic_train_reps: 1
q_nstep: 0  # 0 corresponds to default Q, 1 is r + gamma*Q, etc
name: "coma"